services:
  gemserv:
    build: ./gemserv
    ports:
      - 1965
    volumes:
      - ./allthingslinux.org:/gemroots/allthingslinux.org
      - ./atl.tools:/gemroots/atl.tools
      - ./gemserv:/gemserv
      - ./certs:/certs
